export const students: string[] = [
  'Alexandra',
  'Amaru',
  'Andrés',
  'Anfal',
  'Aris',
  'Asraf',
  'Carmen',
  'Cristian',
  'Darío',
  'David',
  'Elyon',
  'Enma',
  'Francisco',
  'Joel',
  'Lionel',
  'Luna',
  'María',
  'Mario',
  'Marta',
  'Noa',
  'Nubia',
  'Oliver',
  'Pablo',
  'Valentina',
  'Valeria',
  'Zoe Kelly',
  'Zoe Ramírez',
];

export interface Birthday {
  name: string;
  day: number;
  month: number; // 1-12
}

export const birthdays: Birthday[] = [
  { name: 'Alexandra', day: 15, month: 12 },
  { name: 'Amaru', day: 22, month: 1 },
  { name: 'Andrés', day: 8, month: 5 },
  { name: 'Anfal', day: 3, month: 7 },
  { name: 'Aris', day: 19, month: 9 },
  { name: 'Asraf', day: 28, month: 2 },
  { name: 'Carmen', day: 14, month: 4 },
  { name: 'Cristian', day: 7, month: 6 },
  { name: 'Darío', day: 25, month: 8 },
  { name: 'David', day: 11, month: 10 },
  { name: 'Elyon', day: 30, month: 11 },
  { name: 'Enma', day: 5, month: 12 },
  { name: 'Francisco', day: 18, month: 1 },
  { name: 'Joel', day: 9, month: 12 },
  { name: 'Lionel', day: 21, month: 5 },
  { name: 'Luna', day: 16, month: 7 },
  { name: 'María', day: 4, month: 9 },
  { name: 'Mario', day: 27, month: 2 },
  { name: 'Marta', day: 13, month: 4 },
  { name: 'Noa', day: 9, month: 3 },
  { name: 'Nubia', day: 23, month: 3 },
  { name: 'Oliver', day: 7, month: 3 },
  { name: 'Pablo', day: 1, month: 12 },
  { name: 'Valentina', day: 17, month: 11 },
  { name: 'Valeria', day: 29, month: 1 },
  { name: 'Zoe Kelly', day: 12, month: 6 },
  { name: 'Zoe Ramírez', day: 20, month: 5 },
];
